//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Helper {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LogStr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LogStr() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Helper.LogStr", typeof(LogStr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 请手动导航到挑战赛页面 的本地化字符串。
        /// </summary>
        internal static string ManualChaPageNavigate {
            get {
                return ResourceManager.GetString("ManualChaPageNavigate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尚未实现 的本地化字符串。
        /// </summary>
        internal static string NotImplemented {
            get {
                return ResourceManager.GetString("NotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 步骤中止 的本地化字符串。
        /// </summary>
        internal static string StepCancelled {
            get {
                return ResourceManager.GetString("StepCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出现奖励挑战赛 的本地化字符串。
        /// </summary>
        internal static string StepChaAwdFound {
            get {
                return ResourceManager.GetString("StepChaAwdFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已忽略奖励挑战赛 的本地化字符串。
        /// </summary>
        internal static string StepChaAwdIgnored {
            get {
                return ResourceManager.GetString("StepChaAwdIgnored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有奖励挑战赛 的本地化字符串。
        /// </summary>
        internal static string StepChaAwdNotFound {
            get {
                return ResourceManager.GetString("StepChaAwdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已打开奖励挑战赛 的本地化字符串。
        /// </summary>
        internal static string StepChaAwdOpened {
            get {
                return ResourceManager.GetString("StepChaAwdOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 步骤开始【挑战赛】 的本地化字符串。
        /// </summary>
        internal static string StepChaEnter {
            get {
                return ResourceManager.GetString("StepChaEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法打开奖励挑战赛 的本地化字符串。
        /// </summary>
        internal static string StepChaErrAwdFailedOpen {
            get {
                return ResourceManager.GetString("StepChaErrAwdFailedOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 “上一次比赛”不支持“进入奖励挑战赛” 的本地化字符串。
        /// </summary>
        internal static string StepChaErrAwdNotSup {
            get {
                return ResourceManager.GetString("StepChaErrAwdNotSup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法打开关卡 的本地化字符串。
        /// </summary>
        internal static string StepChaErrFailedEnterMatch {
            get {
                return ResourceManager.GetString("StepChaErrFailedEnterMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法退出关卡 的本地化字符串。
        /// </summary>
        internal static string StepChaErrFailedExitMatch {
            get {
                return ResourceManager.GetString("StepChaErrFailedExitMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 比赛时间过长 的本地化字符串。
        /// </summary>
        internal static string StepChaErrGameTimeout {
            get {
                return ResourceManager.GetString("StepChaErrGameTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 忽略奖励挑战赛时出错 的本地化字符串。
        /// </summary>
        internal static string StepChaErrIgnoreAwdFailed {
            get {
                return ResourceManager.GetString("StepChaErrIgnoreAwdFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找不到新比赛 的本地化字符串。
        /// </summary>
        internal static string StepChaErrMatchNoNew {
            get {
                return ResourceManager.GetString("StepChaErrMatchNoNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法退出比赛 的本地化字符串。
        /// </summary>
        internal static string StepChaErrMatchNoOver {
            get {
                return ResourceManager.GetString("StepChaErrMatchNoOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找不到上一次比赛 的本地化字符串。
        /// </summary>
        internal static string StepChaErrMatchNoPrevious {
            get {
                return ResourceManager.GetString("StepChaErrMatchNoPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法开始比赛 的本地化字符串。
        /// </summary>
        internal static string StepChaErrMatchNoStart {
            get {
                return ResourceManager.GetString("StepChaErrMatchNoStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 步骤结束【挑战赛】 的本地化字符串。
        /// </summary>
        internal static string StepChaExit {
            get {
                return ResourceManager.GetString("StepChaExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 比赛结束 的本地化字符串。
        /// </summary>
        internal static string StepChaMatchOver {
            get {
                return ResourceManager.GetString("StepChaMatchOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始奖励挑战赛 {0} 次 的本地化字符串。
        /// </summary>
        internal static string StepChaStartAwdMatchI {
            get {
                return ResourceManager.GetString("StepChaStartAwdMatchI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始第 {0} 次比赛 的本地化字符串。
        /// </summary>
        internal static string StepChaStartMatchI {
            get {
                return ResourceManager.GetString("StepChaStartMatchI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 步骤完成 的本地化字符串。
        /// </summary>
        internal static string StepComplete {
            get {
                return ResourceManager.GetString("StepComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 步骤开始【日常任务】 的本地化字符串。
        /// </summary>
        internal static string StepDailyEnter {
            get {
                return ResourceManager.GetString("StepDailyEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 步骤完成【日常任务】 的本地化字符串。
        /// </summary>
        internal static string StepDailyExit {
            get {
                return ResourceManager.GetString("StepDailyExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 步骤失败【日常任务】 的本地化字符串。
        /// </summary>
        internal static string StepDailyFailed {
            get {
                return ResourceManager.GetString("StepDailyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 步骤开始：测试 的本地化字符串。
        /// </summary>
        internal static string StepDebugBegin {
            get {
                return ResourceManager.GetString("StepDebugBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 步骤完成：测试 的本地化字符串。
        /// </summary>
        internal static string StepDebugEnd {
            get {
                return ResourceManager.GetString("StepDebugEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 步骤出错 的本地化字符串。
        /// </summary>
        internal static string StepErr {
            get {
                return ResourceManager.GetString("StepErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 步骤出错：{0}: {1} 的本地化字符串。
        /// </summary>
        internal static string StepErr_SI {
            get {
                return ResourceManager.GetString("StepErr_SI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 步骤出错【{0}】 的本地化字符串。
        /// </summary>
        internal static string StepErr_Task {
            get {
                return ResourceManager.GetString("StepErr_Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 步骤出错：{0} 的本地化字符串。
        /// </summary>
        internal static string StepErr_X {
            get {
                return ResourceManager.GetString("StepErr_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 截图失败 的本地化字符串。
        /// </summary>
        internal static string StepErrCaptureFailed {
            get {
                return ResourceManager.GetString("StepErrCaptureFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载模板文件失败 的本地化字符串。
        /// </summary>
        internal static string StepErrPatternLoadFailed {
            get {
                return ResourceManager.GetString("StepErrPatternLoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 超时 的本地化字符串。
        /// </summary>
        internal static string StepErrTimeOut {
            get {
                return ResourceManager.GetString("StepErrTimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找不到游戏窗口 的本地化字符串。
        /// </summary>
        internal static string StepErrWndNotExist {
            get {
                return ResourceManager.GetString("StepErrWndNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 步骤异常 的本地化字符串。
        /// </summary>
        internal static string StepException {
            get {
                return ResourceManager.GetString("StepException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 步骤开始【启动游戏】 的本地化字符串。
        /// </summary>
        internal static string StepStartupEnter {
            get {
                return ResourceManager.GetString("StepStartupEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 步骤完成【启动游戏】 的本地化字符串。
        /// </summary>
        internal static string StepStartupExit {
            get {
                return ResourceManager.GetString("StepStartupExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 步骤失败【启动游戏】 的本地化字符串。
        /// </summary>
        internal static string StepStartupFailed {
            get {
                return ResourceManager.GetString("StepStartupFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已停止 的本地化字符串。
        /// </summary>
        internal static string TaskCancelled {
            get {
                return ResourceManager.GetString("TaskCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在停止... 的本地化字符串。
        /// </summary>
        internal static string TaskCancelling {
            get {
                return ResourceManager.GetString("TaskCancelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务完成 的本地化字符串。
        /// </summary>
        internal static string TaskComplete {
            get {
                return ResourceManager.GetString("TaskComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所有步骤均已完成 的本地化字符串。
        /// </summary>
        internal static string TaskCompleteDescription {
            get {
                return ResourceManager.GetString("TaskCompleteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务异常 的本地化字符串。
        /// </summary>
        internal static string TaskErrInternalException {
            get {
                return ResourceManager.GetString("TaskErrInternalException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务出错 的本地化字符串。
        /// </summary>
        internal static string TaskError {
            get {
                return ResourceManager.GetString("TaskError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不能重复运行任务 的本地化字符串。
        /// </summary>
        internal static string TaskErrStartRunning {
            get {
                return ResourceManager.GetString("TaskErrStartRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已暂停：{0} 的本地化字符串。
        /// </summary>
        internal static string TaskPaused {
            get {
                return ResourceManager.GetString("TaskPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务继续 的本地化字符串。
        /// </summary>
        internal static string TaskResume {
            get {
                return ResourceManager.GetString("TaskResume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法启动任务 的本地化字符串。
        /// </summary>
        internal static string TaskWorkStartFailed {
            get {
                return ResourceManager.GetString("TaskWorkStartFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测试: {0}, {1} 的本地化字符串。
        /// </summary>
        internal static string Test_II {
            get {
                return ResourceManager.GetString("Test_II", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知消息：{0} 的本地化字符串。
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
    }
}
