//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinFormsGUI.Strings {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GuiLog {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GuiLog() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinFormsGUI.Strings.GuiLog", typeof(GuiLog).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 开始第 {0} 次比赛 的本地化字符串。
        /// </summary>
        internal static string ChaBegin_I {
            get {
                return ResourceManager.GetString("ChaBegin_I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始奖励挑战赛 {0} 次 的本地化字符串。
        /// </summary>
        internal static string ChaBeginAdd_I {
            get {
                return ResourceManager.GetString("ChaBeginAdd_I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务结束【挑战赛】 的本地化字符串。
        /// </summary>
        internal static string ChaExit {
            get {
                return ResourceManager.GetString("ChaExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出现奖励挑战赛 的本地化字符串。
        /// </summary>
        internal static string ChaFindAdd {
            get {
                return ResourceManager.GetString("ChaFindAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已忽略奖励挑战赛 的本地化字符串。
        /// </summary>
        internal static string ChaIgnoredAdd {
            get {
                return ResourceManager.GetString("ChaIgnoredAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有奖励挑战赛 的本地化字符串。
        /// </summary>
        internal static string ChaNotFindAdd {
            get {
                return ResourceManager.GetString("ChaNotFindAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已打开奖励挑战赛 的本地化字符串。
        /// </summary>
        internal static string ChaOpenedAdd {
            get {
                return ResourceManager.GetString("ChaOpenedAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 比赛结束 的本地化字符串。
        /// </summary>
        internal static string ChaOver {
            get {
                return ResourceManager.GetString("ChaOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务开始【挑战赛】 的本地化字符串。
        /// </summary>
        internal static string ChaStart {
            get {
                return ResourceManager.GetString("ChaStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建挂钩失败 的本地化字符串。
        /// </summary>
        internal static string HookFailed {
            get {
                return ResourceManager.GetString("HookFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请手动导航到比赛 的本地化字符串。
        /// </summary>
        internal static string ManualNavigateToChallengePage {
            get {
                return ResourceManager.GetString("ManualNavigateToChallengePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尚未实现 的本地化字符串。
        /// </summary>
        internal static string NotImplemented {
            get {
                return ResourceManager.GetString("NotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已暂停：{0} 的本地化字符串。
        /// </summary>
        internal static string Paused {
            get {
                return ResourceManager.GetString("Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务完成 的本地化字符串。
        /// </summary>
        internal static string TaskComplete {
            get {
                return ResourceManager.GetString("TaskComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务开始【日常任务】 的本地化字符串。
        /// </summary>
        internal static string TaskDailyBegin {
            get {
                return ResourceManager.GetString("TaskDailyBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务完成【日常任务】 的本地化字符串。
        /// </summary>
        internal static string TaskDailyComplete {
            get {
                return ResourceManager.GetString("TaskDailyComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务失败【日常任务】 的本地化字符串。
        /// </summary>
        internal static string TaskDailyFailed {
            get {
                return ResourceManager.GetString("TaskDailyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务出错 的本地化字符串。
        /// </summary>
        internal static string TaskErr {
            get {
                return ResourceManager.GetString("TaskErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务出错：{0}: {1} 的本地化字符串。
        /// </summary>
        internal static string TaskErr_F_SI {
            get {
                return ResourceManager.GetString("TaskErr_F_SI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务出错：{0} 的本地化字符串。
        /// </summary>
        internal static string TaskErr_Format {
            get {
                return ResourceManager.GetString("TaskErr_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务出错【{0}】 的本地化字符串。
        /// </summary>
        internal static string TaskErr_Task {
            get {
                return ResourceManager.GetString("TaskErr_Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 “上一次比赛”不支持进入“奖励挑战赛” 的本地化字符串。
        /// </summary>
        internal static string TaskErrChaAddNotSup {
            get {
                return ResourceManager.GetString("TaskErrChaAddNotSup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 忽略奖励挑战赛出错 的本地化字符串。
        /// </summary>
        internal static string TaskErrChaIgnoreAddFailed {
            get {
                return ResourceManager.GetString("TaskErrChaIgnoreAddFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法退出挑战 的本地化字符串。
        /// </summary>
        internal static string TaskErrChaNoEnd {
            get {
                return ResourceManager.GetString("TaskErrChaNoEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法进入比赛 的本地化字符串。
        /// </summary>
        internal static string TaskErrChaNoEnter {
            get {
                return ResourceManager.GetString("TaskErrChaNoEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找不到新比赛 的本地化字符串。
        /// </summary>
        internal static string TaskErrChaNoNew {
            get {
                return ResourceManager.GetString("TaskErrChaNoNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法退出比赛 的本地化字符串。
        /// </summary>
        internal static string TaskErrChaNoOver {
            get {
                return ResourceManager.GetString("TaskErrChaNoOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找不到上一次比赛 的本地化字符串。
        /// </summary>
        internal static string TaskErrChaNoPri {
            get {
                return ResourceManager.GetString("TaskErrChaNoPri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法开始挑战 的本地化字符串。
        /// </summary>
        internal static string TaskErrChaNoStart {
            get {
                return ResourceManager.GetString("TaskErrChaNoStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开奖励挑战赛出错 的本地化字符串。
        /// </summary>
        internal static string TaskErrChaOpenAddFailed {
            get {
                return ResourceManager.GetString("TaskErrChaOpenAddFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 挑战超时 的本地化字符串。
        /// </summary>
        internal static string TaskErrChaTimeOut {
            get {
                return ResourceManager.GetString("TaskErrChaTimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 超时 的本地化字符串。
        /// </summary>
        internal static string TaskErrCommonTLE {
            get {
                return ResourceManager.GetString("TaskErrCommonTLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载模板文件失败 的本地化字符串。
        /// </summary>
        internal static string TaskErrFailedToLoadTemplateFile {
            get {
                return ResourceManager.GetString("TaskErrFailedToLoadTemplateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法截图 的本地化字符串。
        /// </summary>
        internal static string TaskErrNoCap {
            get {
                return ResourceManager.GetString("TaskErrNoCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找不到游戏窗口 的本地化字符串。
        /// </summary>
        internal static string TaskErrNoWnd {
            get {
                return ResourceManager.GetString("TaskErrNoWnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务异常 的本地化字符串。
        /// </summary>
        internal static string TaskException {
            get {
                return ResourceManager.GetString("TaskException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务开始【启动游戏】 的本地化字符串。
        /// </summary>
        internal static string TaskStartUpBegin {
            get {
                return ResourceManager.GetString("TaskStartUpBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务完成【启动游戏】 的本地化字符串。
        /// </summary>
        internal static string TaskStartUpComplete {
            get {
                return ResourceManager.GetString("TaskStartUpComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务失败【启动游戏】 的本地化字符串。
        /// </summary>
        internal static string TaskStartUpFailed {
            get {
                return ResourceManager.GetString("TaskStartUpFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务中止 的本地化字符串。
        /// </summary>
        internal static string TaskStop {
            get {
                return ResourceManager.GetString("TaskStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测试: {0}, {1} 的本地化字符串。
        /// </summary>
        internal static string Test_II {
            get {
                return ResourceManager.GetString("Test_II", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始任务：测试 的本地化字符串。
        /// </summary>
        internal static string TestTaskBegin {
            get {
                return ResourceManager.GetString("TestTaskBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完成任务：测试 的本地化字符串。
        /// </summary>
        internal static string TestTaskEnd {
            get {
                return ResourceManager.GetString("TestTaskEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知消息：{0} 的本地化字符串。
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法启动任务 的本地化字符串。
        /// </summary>
        internal static string WorkCanNotStartWork {
            get {
                return ResourceManager.GetString("WorkCanNotStartWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工作完成 的本地化字符串。
        /// </summary>
        internal static string WorkComplete {
            get {
                return ResourceManager.GetString("WorkComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所有任务均已完成 的本地化字符串。
        /// </summary>
        internal static string WorkCompleteDescribtion {
            get {
                return ResourceManager.GetString("WorkCompleteDescribtion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工作出错 的本地化字符串。
        /// </summary>
        internal static string WorkError {
            get {
                return ResourceManager.GetString("WorkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工作异常 的本地化字符串。
        /// </summary>
        internal static string WorkErrorInternalException {
            get {
                return ResourceManager.GetString("WorkErrorInternalException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务继续 的本地化字符串。
        /// </summary>
        internal static string WorkResumed {
            get {
                return ResourceManager.GetString("WorkResumed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不能重复运行任务 的本地化字符串。
        /// </summary>
        internal static string WorkStartErrRunning {
            get {
                return ResourceManager.GetString("WorkStartErrRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已停止 的本地化字符串。
        /// </summary>
        internal static string WorkStopped {
            get {
                return ResourceManager.GetString("WorkStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在停止... 的本地化字符串。
        /// </summary>
        internal static string WorkStopping {
            get {
                return ResourceManager.GetString("WorkStopping", resourceCulture);
            }
        }
    }
}
