//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinFormsGUI.Strings {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LogEvent {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LogEvent() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinFormsGUI.Strings.LogEvent", typeof(LogEvent).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 开始第 {0} 次比赛 的本地化字符串。
        /// </summary>
        internal static string Challenge_BeginNum {
            get {
                return ResourceManager.GetString("Challenge_BeginNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 挑战结束 的本地化字符串。
        /// </summary>
        internal static string Challenge_End {
            get {
                return ResourceManager.GetString("Challenge_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 进入奖励挑战赛 的本地化字符串。
        /// </summary>
        internal static string Challenge_EnterAdd {
            get {
                return ResourceManager.GetString("Challenge_EnterAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 进入上一次比赛 的本地化字符串。
        /// </summary>
        internal static string Challenge_EnterLast {
            get {
                return ResourceManager.GetString("Challenge_EnterLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 进入新比赛 的本地化字符串。
        /// </summary>
        internal static string Challenge_EnterNew {
            get {
                return ResourceManager.GetString("Challenge_EnterNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务结束: 挑战赛 的本地化字符串。
        /// </summary>
        internal static string Challenge_Exit {
            get {
                return ResourceManager.GetString("Challenge_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出现奖励挑战赛 的本地化字符串。
        /// </summary>
        internal static string Challenge_FindAdd {
            get {
                return ResourceManager.GetString("Challenge_FindAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已忽略奖励挑战赛 的本地化字符串。
        /// </summary>
        internal static string Challenge_IgnoredAdd {
            get {
                return ResourceManager.GetString("Challenge_IgnoredAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有奖励挑战赛 的本地化字符串。
        /// </summary>
        internal static string Challenge_NotFindAdd {
            get {
                return ResourceManager.GetString("Challenge_NotFindAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已打开奖励挑战赛 的本地化字符串。
        /// </summary>
        internal static string Challenge_OpenedAdd {
            get {
                return ResourceManager.GetString("Challenge_OpenedAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 比赛结束 的本地化字符串。
        /// </summary>
        internal static string Challenge_Over {
            get {
                return ResourceManager.GetString("Challenge_Over", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始挑战 的本地化字符串。
        /// </summary>
        internal static string Challenge_Play {
            get {
                return ResourceManager.GetString("Challenge_Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在退出比赛 的本地化字符串。
        /// </summary>
        internal static string Challenge_Quiting {
            get {
                return ResourceManager.GetString("Challenge_Quiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务开始: 挑战赛 的本地化字符串。
        /// </summary>
        internal static string Challenge_Start {
            get {
                return ResourceManager.GetString("Challenge_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 等待结算 的本地化字符串。
        /// </summary>
        internal static string Challenge_WaitForEnd {
            get {
                return ResourceManager.GetString("Challenge_WaitForEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务出错 的本地化字符串。
        /// </summary>
        internal static string Task_Error {
            get {
                return ResourceManager.GetString("Task_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务异常 的本地化字符串。
        /// </summary>
        internal static string Task_Exception {
            get {
                return ResourceManager.GetString("Task_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务中止 的本地化字符串。
        /// </summary>
        internal static string Task_Stop {
            get {
                return ResourceManager.GetString("Task_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未描述的事件：{0} 的本地化字符串。
        /// </summary>
        internal static string UNKNOWN {
            get {
                return ResourceManager.GetString("UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不能重复运行任务 的本地化字符串。
        /// </summary>
        internal static string Work_AlreadyRunning {
            get {
                return ResourceManager.GetString("Work_AlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法截图 的本地化字符串。
        /// </summary>
        internal static string Work_CanNotCapture {
            get {
                return ResourceManager.GetString("Work_CanNotCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找不到DOAXVV窗口 的本地化字符串。
        /// </summary>
        internal static string Work_CanNotFindWnd {
            get {
                return ResourceManager.GetString("Work_CanNotFindWnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法启动任务 的本地化字符串。
        /// </summary>
        internal static string Work_CanNotStartWork {
            get {
                return ResourceManager.GetString("Work_CanNotStartWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工作出错 的本地化字符串。
        /// </summary>
        internal static string Work_Error {
            get {
                return ResourceManager.GetString("Work_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工作异常 的本地化字符串。
        /// </summary>
        internal static string Work_Exception {
            get {
                return ResourceManager.GetString("Work_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已停止 的本地化字符串。
        /// </summary>
        internal static string Work_Stopped {
            get {
                return ResourceManager.GetString("Work_Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在停止... 的本地化字符串。
        /// </summary>
        internal static string Work_Stopping {
            get {
                return ResourceManager.GetString("Work_Stopping", resourceCulture);
            }
        }
    }
}
