//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinFormsGUI.Strings {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LogStr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LogStr() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinFormsGUI.Strings.LogStr", typeof(LogStr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 无法截图 的本地化字符串。
        /// </summary>
        internal static string Task_CanNotCapture {
            get {
                return ResourceManager.GetString("Task_CanNotCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找不到DOAXVV窗口 的本地化字符串。
        /// </summary>
        internal static string Task_CanNotFindWnd {
            get {
                return ResourceManager.GetString("Task_CanNotFindWnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 “上一次比赛”不支持进入“奖励挑战赛” 的本地化字符串。
        /// </summary>
        internal static string Task_Challenge_AddNotSup {
            get {
                return ResourceManager.GetString("Task_Challenge_AddNotSup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 忽略奖励挑战赛出错 的本地化字符串。
        /// </summary>
        internal static string Task_Challenge_IgnoreAddFailed {
            get {
                return ResourceManager.GetString("Task_Challenge_IgnoreAddFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FP耗尽 的本地化字符串。
        /// </summary>
        internal static string Task_Challenge_LowFP {
            get {
                return ResourceManager.GetString("Task_Challenge_LowFP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法退出挑战 的本地化字符串。
        /// </summary>
        internal static string Task_Challenge_NoEnd {
            get {
                return ResourceManager.GetString("Task_Challenge_NoEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法进入比赛 的本地化字符串。
        /// </summary>
        internal static string Task_Challenge_NoEnter {
            get {
                return ResourceManager.GetString("Task_Challenge_NoEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找不到上一次比赛 的本地化字符串。
        /// </summary>
        internal static string Task_Challenge_NoLast {
            get {
                return ResourceManager.GetString("Task_Challenge_NoLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找不到新比赛 的本地化字符串。
        /// </summary>
        internal static string Task_Challenge_NoNew {
            get {
                return ResourceManager.GetString("Task_Challenge_NoNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法退出比赛 的本地化字符串。
        /// </summary>
        internal static string Task_Challenge_NoOver {
            get {
                return ResourceManager.GetString("Task_Challenge_NoOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法开始挑战 的本地化字符串。
        /// </summary>
        internal static string Task_Challenge_NoStart {
            get {
                return ResourceManager.GetString("Task_Challenge_NoStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开奖励挑战赛出错 的本地化字符串。
        /// </summary>
        internal static string Task_Challenge_OpenAddFailed {
            get {
                return ResourceManager.GetString("Task_Challenge_OpenAddFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 挑战超时 的本地化字符串。
        /// </summary>
        internal static string Task_Challenge_TimeOut {
            get {
                return ResourceManager.GetString("Task_Challenge_TimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载模板文件失败 的本地化字符串。
        /// </summary>
        internal static string Task_FailedToLoadTemplateFile {
            get {
                return ResourceManager.GetString("Task_FailedToLoadTemplateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未描述的错误：{0} 的本地化字符串。
        /// </summary>
        internal static string UNKNOWN {
            get {
                return ResourceManager.GetString("UNKNOWN", resourceCulture);
            }
        }
    }
}
