//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinFormsGUI.Strings {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Main {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Main() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinFormsGUI.Strings.Main", typeof(Main).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Link Start! 的本地化字符串。
        /// </summary>
        internal static string Btn_Main_Start {
            get {
                return ResourceManager.GetString("Btn_Main_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止 的本地化字符串。
        /// </summary>
        internal static string Btn_Main_Stop {
            get {
                return ResourceManager.GetString("Btn_Main_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找不到名为 &quot;{0}&quot; 的字符串。 的本地化字符串。
        /// </summary>
        internal static string NoSuchString {
            get {
                return ResourceManager.GetString("NoSuchString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 核心模块初始化失败 的本地化字符串。
        /// </summary>
        internal static string ProgramCoreInitializationFailed {
            get {
                return ResourceManager.GetString("ProgramCoreInitializationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法创建日志文件 的本地化字符串。
        /// </summary>
        internal static string ProgramCoreInitializationFailed_CoreLogOpenFailed {
            get {
                return ResourceManager.GetString("ProgramCoreInitializationFailed_CoreLogOpenFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法读取模板列表 的本地化字符串。
        /// </summary>
        internal static string ProgramCoreInitializationFailed_LoadTemplateListFailed {
            get {
                return ResourceManager.GetString("ProgramCoreInitializationFailed_LoadTemplateListFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知原因 的本地化字符串。
        /// </summary>
        internal static string ProgramCoreInitializationFailed_UnknownReason {
            get {
                return ResourceManager.GetString("ProgramCoreInitializationFailed_UnknownReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前仍有任务进行，确定要退出吗？ 的本地化字符串。
        /// </summary>
        internal static string QueryClose {
            get {
                return ResourceManager.GetString("QueryClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [null] 的本地化字符串。
        /// </summary>
        internal static string Task000 {
            get {
                return ResourceManager.GetString("Task000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动游戏 的本地化字符串。
        /// </summary>
        internal static string Task001 {
            get {
                return ResourceManager.GetString("Task001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日常任务 的本地化字符串。
        /// </summary>
        internal static string Task002 {
            get {
                return ResourceManager.GetString("Task002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 岛主房间 的本地化字符串。
        /// </summary>
        internal static string Task003 {
            get {
                return ResourceManager.GetString("Task003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 挑战赛 的本地化字符串。
        /// </summary>
        internal static string Task004 {
            get {
                return ResourceManager.GetString("Task004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 温泉 的本地化字符串。
        /// </summary>
        internal static string Task005 {
            get {
                return ResourceManager.GetString("Task005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 领取奖励 的本地化字符串。
        /// </summary>
        internal static string Task006 {
            get {
                return ResourceManager.GetString("Task006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出游戏 的本地化字符串。
        /// </summary>
        internal static string Task007 {
            get {
                return ResourceManager.GetString("Task007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 【旧】刷挑战赛 的本地化字符串。
        /// </summary>
        internal static string Task008 {
            get {
                return ResourceManager.GetString("Task008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Test 的本地化字符串。
        /// </summary>
        internal static string Task666 {
            get {
                return ResourceManager.GetString("Task666", resourceCulture);
            }
        }
    }
}
