//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinFormsGUI.Strings {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Main {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Main() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinFormsGUI.Strings.Main", typeof(Main).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 LOG_Challenge_EnterAdd 的本地化字符串。
        /// </summary>
        internal static string LOG_Challenge_EnterAdd {
            get {
                return ResourceManager.GetString("LOG_Challenge_EnterAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log_Challenge_Exit 的本地化字符串。
        /// </summary>
        internal static string Log_Challenge_Exit {
            get {
                return ResourceManager.GetString("Log_Challenge_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LOG_Challenge_FindAdd 的本地化字符串。
        /// </summary>
        internal static string LOG_Challenge_FindAdd {
            get {
                return ResourceManager.GetString("LOG_Challenge_FindAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LOG_Challenge_IgnoredAdd 的本地化字符串。
        /// </summary>
        internal static string LOG_Challenge_IgnoredAdd {
            get {
                return ResourceManager.GetString("LOG_Challenge_IgnoredAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LOG_Challenge_NotFindAdd 的本地化字符串。
        /// </summary>
        internal static string LOG_Challenge_NotFindAdd {
            get {
                return ResourceManager.GetString("LOG_Challenge_NotFindAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LOG_Challenge_OpenedAdd 的本地化字符串。
        /// </summary>
        internal static string LOG_Challenge_OpenedAdd {
            get {
                return ResourceManager.GetString("LOG_Challenge_OpenedAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log_Challenge_Over 的本地化字符串。
        /// </summary>
        internal static string Log_Challenge_Over {
            get {
                return ResourceManager.GetString("Log_Challenge_Over", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log_Task_Challenge_LowFP 的本地化字符串。
        /// </summary>
        internal static string Log_Task_Challenge_LowFP {
            get {
                return ResourceManager.GetString("Log_Task_Challenge_LowFP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log_Task_Challenge_NoEnd 的本地化字符串。
        /// </summary>
        internal static string Log_Task_Challenge_NoEnd {
            get {
                return ResourceManager.GetString("Log_Task_Challenge_NoEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log_Task_Challenge_NoEnter 的本地化字符串。
        /// </summary>
        internal static string Log_Task_Challenge_NoEnter {
            get {
                return ResourceManager.GetString("Log_Task_Challenge_NoEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log_Task_Challenge_NoLast 的本地化字符串。
        /// </summary>
        internal static string Log_Task_Challenge_NoLast {
            get {
                return ResourceManager.GetString("Log_Task_Challenge_NoLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log_Task_Challenge_NoNew 的本地化字符串。
        /// </summary>
        internal static string Log_Task_Challenge_NoNew {
            get {
                return ResourceManager.GetString("Log_Task_Challenge_NoNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log_Task_Challenge_NoOver 的本地化字符串。
        /// </summary>
        internal static string Log_Task_Challenge_NoOver {
            get {
                return ResourceManager.GetString("Log_Task_Challenge_NoOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log_Task_Challenge_NoStart 的本地化字符串。
        /// </summary>
        internal static string Log_Task_Challenge_NoStart {
            get {
                return ResourceManager.GetString("Log_Task_Challenge_NoStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log_Task_Challenge_TimeOut 的本地化字符串。
        /// </summary>
        internal static string Log_Task_Challenge_TimeOut {
            get {
                return ResourceManager.GetString("Log_Task_Challenge_TimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log_Task_Exception 的本地化字符串。
        /// </summary>
        internal static string Log_Task_Exception {
            get {
                return ResourceManager.GetString("Log_Task_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log_Task_Stop 的本地化字符串。
        /// </summary>
        internal static string Log_Task_Stop {
            get {
                return ResourceManager.GetString("Log_Task_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log_UNKNOWN: {0} 的本地化字符串。
        /// </summary>
        internal static string Log_UNKNOWN {
            get {
                return ResourceManager.GetString("Log_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Main_Btn_Start 的本地化字符串。
        /// </summary>
        internal static string Main_Btn_Start {
            get {
                return ResourceManager.GetString("Main_Btn_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Main_Btn_Stop 的本地化字符串。
        /// </summary>
        internal static string Main_Btn_Stop {
            get {
                return ResourceManager.GetString("Main_Btn_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Main_Log_CanNotCapture 的本地化字符串。
        /// </summary>
        internal static string Main_Log_CanNotCapture {
            get {
                return ResourceManager.GetString("Main_Log_CanNotCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Main_Log_CanNotFindWnd 的本地化字符串。
        /// </summary>
        internal static string Main_Log_CanNotFindWnd {
            get {
                return ResourceManager.GetString("Main_Log_CanNotFindWnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Main_Log_CanNotStartWork 的本地化字符串。
        /// </summary>
        internal static string Main_Log_CanNotStartWork {
            get {
                return ResourceManager.GetString("Main_Log_CanNotStartWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Main_Log_Challenge_BeginNum{0} 的本地化字符串。
        /// </summary>
        internal static string Main_Log_Challenge_BeginNum {
            get {
                return ResourceManager.GetString("Main_Log_Challenge_BeginNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Main_Log_Challenge_End 的本地化字符串。
        /// </summary>
        internal static string Main_Log_Challenge_End {
            get {
                return ResourceManager.GetString("Main_Log_Challenge_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Main_Log_Challenge_EnterLast 的本地化字符串。
        /// </summary>
        internal static string Main_Log_Challenge_EnterLast {
            get {
                return ResourceManager.GetString("Main_Log_Challenge_EnterLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Main_Log_Challenge_EnterNew 的本地化字符串。
        /// </summary>
        internal static string Main_Log_Challenge_EnterNew {
            get {
                return ResourceManager.GetString("Main_Log_Challenge_EnterNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Main_Log_Challenge_Play 的本地化字符串。
        /// </summary>
        internal static string Main_Log_Challenge_Play {
            get {
                return ResourceManager.GetString("Main_Log_Challenge_Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Main_Log_Challenge_Quiting 的本地化字符串。
        /// </summary>
        internal static string Main_Log_Challenge_Quiting {
            get {
                return ResourceManager.GetString("Main_Log_Challenge_Quiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Main_Log_Challenge_Start 的本地化字符串。
        /// </summary>
        internal static string Main_Log_Challenge_Start {
            get {
                return ResourceManager.GetString("Main_Log_Challenge_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Main_Log_Challenge_WaitForEnd 的本地化字符串。
        /// </summary>
        internal static string Main_Log_Challenge_WaitForEnd {
            get {
                return ResourceManager.GetString("Main_Log_Challenge_WaitForEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Main_Log_ExceptionInWork 的本地化字符串。
        /// </summary>
        internal static string Main_Log_ExceptionInWork {
            get {
                return ResourceManager.GetString("Main_Log_ExceptionInWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Main_Log_TaskError 的本地化字符串。
        /// </summary>
        internal static string Main_Log_TaskError {
            get {
                return ResourceManager.GetString("Main_Log_TaskError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Main_Log_WorkAlreadyRunning 的本地化字符串。
        /// </summary>
        internal static string Main_Log_WorkAlreadyRunning {
            get {
                return ResourceManager.GetString("Main_Log_WorkAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Main_Log_WorkError 的本地化字符串。
        /// </summary>
        internal static string Main_Log_WorkError {
            get {
                return ResourceManager.GetString("Main_Log_WorkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Main_Log_WorkStopped 的本地化字符串。
        /// </summary>
        internal static string Main_Log_WorkStopped {
            get {
                return ResourceManager.GetString("Main_Log_WorkStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Main_Log_WorkStopping 的本地化字符串。
        /// </summary>
        internal static string Main_Log_WorkStopping {
            get {
                return ResourceManager.GetString("Main_Log_WorkStopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 STR_Task_Challenge_AddNotSup 的本地化字符串。
        /// </summary>
        internal static string STR_Task_Challenge_AddNotSup {
            get {
                return ResourceManager.GetString("STR_Task_Challenge_AddNotSup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 STR_Task_Challenge_IgnoreAddFailed 的本地化字符串。
        /// </summary>
        internal static string STR_Task_Challenge_IgnoreAddFailed {
            get {
                return ResourceManager.GetString("STR_Task_Challenge_IgnoreAddFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 STR_Task_Challenge_OpenAddFailed 的本地化字符串。
        /// </summary>
        internal static string STR_Task_Challenge_OpenAddFailed {
            get {
                return ResourceManager.GetString("STR_Task_Challenge_OpenAddFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 STR_UNKNOWN: {0} 的本地化字符串。
        /// </summary>
        internal static string STR_UNKNOWN {
            get {
                return ResourceManager.GetString("STR_UNKNOWN", resourceCulture);
            }
        }
    }
}
